"""empty message

Revision ID: 4b8a95be7508
Revises: 5fe51b2826ad
Create Date: 2021-08-23 00:17:39.364065

"""

# revision identifiers, used by Alembic.
revision = '4b8a95be7508'
down_revision = '5fe51b2826ad'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pitch', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pitch', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
