"""empty message

Revision ID: 5fe51b2826ad
Revises: f0538225efd3
Create Date: 2021-08-23 00:13:45.803481

"""

# revision identifiers, used by Alembic.
revision = '5fe51b2826ad'
down_revision = 'f0538225efd3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pitch', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pitch', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
