"""empty message

Revision ID: f0538225efd3
Revises: 4b4604d66bb5
Create Date: 2021-08-22 21:36:12.376499

"""

# revision identifiers, used by Alembic.
revision = 'f0538225efd3'
down_revision = '4b4604d66bb5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'pitch', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pitch', type_='foreignkey')
    op.drop_column('pitch', 'user_id')
    # ### end Alembic commands ###
